# Plot and save all xvg files generated by gromacs in given folder
# Usage:
#   python plotxvg.py folder




import pandas as pd
import matplotlib.pyplot as plt
import os, sys

folder = sys.argv[1]

for file in os.listdir(folder):
    print(file)
    if '.xvg' not in file:
        continue
    toplot = pd.read_csv('{}/{}'.format(folder,file), delimiter='  ',header=None, skiprows=24)
    plt.plot(toplot[1])
    plt.savefig("{}/{}.png".format(folder, file), bbox_inches="tight")
    plt.clf()